spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: user
      password: password # ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 29000 #27017
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
  
  

